name: clippy_examples
description: Examples
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.0.0-dev <3.0.0"

dependencies:
  clippy:
    path: "../"

dev_dependencies:
  build_runner: ^2.3.2
  build_test: ^2.1.5
  build_web_compilers: ^3.2.7
  test: ^1.22.0
