name: clippy
description: Access system clipboard in Dart (Server & Browser).
version: 1.0.1
homepage: https://github.com/andresaraujo/clippy

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.8.2

dev_dependencies:
  test: ^1.22.0
